FROM python:3.11-slim
WORKDIR /app
COPY cliente.py testes.py graficos.py requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONIOENCODING=utf-8
CMD ["python3", "cliente.py"]
