FROM httpd:2.4

RUN sed -i \
    's/#LoadModule status_module/LoadModule status_module/' \
    /usr/local/apache2/conf/httpd.conf

RUN echo "ServerName localhost" >> /usr/local/apache2/conf/httpd.conf

RUN echo "" >> /usr/local/apache2/conf/httpd.conf && \
    echo "<Location /server-status>" >> /usr/local/apache2/conf/httpd.conf && \
    echo "    SetHandler server-status" >> /usr/local/apache2/conf/httpd.conf && \
    echo "    Require all granted" >> /usr/local/apache2/conf/httpd.conf && \
    echo "</Location>" >> /usr/local/apache2/conf/httpd.conf