# Apenas as linhas cruciais que devem estar descomentadas/adicionadas no httpd.conf padrão:
LoadModule status_module modules/mod_status.so

<Location "/server-status">
    SetHandler server-status
    Require all granted
</Location>