global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "nginx_job"
    static_configs:
      - targets: ["60.45.0.12:9113"] # IP do nginx-exporter

  - job_name: "apache_job"
    static_configs:
      - targets: ["60.45.0.22:9117"] # IP do apache-exporter
